### ISSUE TITLE
出现白屏

### ISSUE THREAD

**Issue by ZengJingWei** [WangGanxin/LoadDataLayout#3]
LoadDataLayout配合WebView使用 为啥出现白屏，而不用LoadDataLayout换成SwipeLoadDataLayout就不会出现，我的整个页面是一个fragment

**Comment by WangGanxin** [comment]
LoadDataLayout直接包裹WebView使用是没有问题的，你看下你的fragment页面状态或数据是否丢失了

**Comment by WangGanxin** [comment]
@ZengJingWei  LoadDataLayout直接包裹WebView使用是没有问题的，你看下你的fragment页面状态或数据是否丢失了
